### ISSUE TITLE
allow to skip filter on certain requests

### ISSUE THREAD

**Issue by brian-ally** [loadsys/CakePHP-Serializers#114]
It would be nice to be able to configure certain controllers/actions to be skipped in DeserializerFilter. For now i've simply hacked it in myself:
```
if ($request->params['controller'] == 'users' && $request->params['action'] == 'token') {
	return;
}
```
Certainly not a winning solution! I'm trying to figure out the best way to be able to read plugin config from within the filter. Any ideas?

**Comment by jtyost2** [comment]
There is a good way to skip Serialization actually, don't engage the ViewClass on the controller or action in question.

We do this on occasion at the controller level, where we swap the View Class for [Cake's JSON view class](http://book.cakephp.org/2.0/en/views/json-and-xml-views.html) for things that we want to just `json_encode` and output.

You can also use the `$renderAs` property in the controller to control this.

Documentation on this setup is here: https://github.com/loadsys/CakePHP-Serializers/blob/master/Docs/SERIALIZE_README.md#basic-controller-setup---serializing

**Comment by beporter** [comment]
@jtyost2 Does changing the view class affect **de**serialization though? Seems like the DispatchFilter would have already run...

**Comment by beporter** [comment]
@brianally: If I'm understanding you correctly, this is definitely an area where the plugin just isn't full-featured enough yet. It currently makes the assumption that **all** inbound traffic will be deserialized, which works only if your entire Cake app is an API, I guess, but that was our starting use case so that's how we built it first.

As a work around, I wonder if it might not be possible to selectively enable the filter directly in your `bootstrap.php`, so that it's not even loaded for the requests you want to avoid. I'm thinking something like this rough pseudo code (I haven't tried this-- I'm just sharing the idea):

``` php
// Config/bootstrap.php

// Set up default filters for all requests.
Configure::write('Dispatcher.filters', array(
    'AssetDispatcher',
    'CacheDispatcher',
));

// Define a list of controllers where we want deserialization to occur.
$deserializeControllers = ['products', 'stuff', 'blah'];

// Get the current request so we can check the controller.
$request = new CakeRequest(); // No idea if this will work here.

// Only include the Deserializer filter if the current controller is in our list.
if (in_array($request->params->something['controller'], $deserializeControllers)) {
    Configure::write('Dispatcher.filters', array_merge(
        Configure::read('Dispatcher.filters'), // Keep the existing filter list,
        array(
            'Serializers.DeserializerFilter', // but append the Deserializer.
        )
    ));
}
```

I recognize this is kind of crude, but I'm keen to help you get up and running at least for the time being. I'm sure we'd be open to discussing how best to improve the package so it could handle this itself more gracefully. Maybe we could create a `Configure::read('Serializers.deserializer')` key that the DispatchFilter could use somehow like the above example? We'd have to come up with some kind of syntax for whitelisting/blacklisting controllers or possibly even individual actions.

**Comment by jtyost2** [comment]
Whoops, thanks @beporter for correcting my mistake.

Sorry @brian-ally I misread.

**Comment by brian-ally** [comment]
@jtyost2 Yep, the problem is with the deserialization.

@beporter Nice idea but creating a CakeRequest object won't work there. bootstrap.php is included from within webroot/index.php, and at the very bottom is where Dispatcher is created, along with the req & res.

What i was thinking of is something like:
```
// bootstrap.php

Configure::write('Serializers.skip', ['users' => ['token']]);


// Plugin/Serializers/Routing/Filter/DeserializerFilter.php

$skip = Configure::read('Serializers.skip');

if ( $skip ) {
	if ( !is_array($skip) ) $skip = array($skip);

	// array keys should be controller names
	$controllers = array_keys($skip);

	foreach( $controllers as $controller ) {

		// does it match the request?
		if ( $controller == $request->params['controller'] ) {

			// if config for this controller name is an array of action names
			// then we want to skip only those actions
			if ( !empty($skip[$controller]) && is_array($skip[$controller]) ) {

				foreach( $skip[$controller] as $action ) {
					// if action matched do nothing
					if ( $action == $request->params['action'] ) {
						return;
					}
				}
			} else {
				// controller matched but no actions specified
				return;
			}
		}
	}
}
```
So, one could provide an array of controller names for those that should be skipped. If only certain actions should be skipped then an array of action names should be provided.

This appears to be working, although i haven't written tests. But I seem to have another issue in Ember causing the page to reload so i can't be certain of anything. I'm currently dealing with the joy that is getting authentication working in Ember.js. Not fun.

**Comment by beporter** [comment]
@jtyost2 and I were discussing this issue in more detail yesterday, and he suggested an alternative solution that could prove to be much cleaner and easier to understand. 

The short of it is that both the DispatchFilter used for automatic deserializing, and the View class used for automatic serializing, could use the `Accept` ([and/or `Content-Type`](http://webmasters.stackexchange.com/a/31231)) header(s) from the request to determine whether they should engage or not. This mirrors how Cake's own built in json processing works already, and allows the Cake app to respond more elegantly to `text/html` requests vs `application/json` or even `application/vnd.api+json` for JSON-API specifically.

Justin had actually already stubbed issue #107 for this purpose, but since this project is still in its infancy (relatively speaking) and not widely used yet he didn't fully flesh this idea out there. If that approach sounds like it would work in place of manual configuration (like either yours or my examples), then perhaps we can continue the conversation there? If on the other hand there's still a need for an auxiliary "manual control" configuration, then we can keep this thread open and discuss the implementation more, but personally I like the idea using a "natural" property of the request a lot better than having more setup and maintenance steps.

Good luck with your Ember implementation!

**Comment by brian-ally** [comment]
That seems like a much better approach. Much, much cleaner. I'm pretty stacked up right now myself but i'll give it some thought.
