### ISSUE TITLE
Pluralizing belongsTo

### ISSUE THREAD

**Issue by brianally** [loadsys/CakePHP-Serializers#126]
User belongsTo Agency. User has an agency_id column, so there is only ever one Agency. However, i'm getting this:

```
Array (
  [id] => 2
  [created] => 2015-05-27 20:45:20
  [name] => foo
  [email] => foo@bar.net
  [agency_id] => 6
  [agencies] => Array (
    [0] => Array (
      [id] => 6
      [created] => 2015-05-20 16:32:53
      [modified] => 2015-05-20 16:32:53
      ...
      )
  )
)
```

The example for belongsTo in the Ember-Data docs shows that it should be a singular name:

```
{
  "post": {
    "id": "1"
    "title": "Rails is omakase",
    "author": {
      "id": "2"
      "name": "dhh"
    }
  }
}
```

The comment for this plugin's correctSubSerializedModels() says:

```
corrects the key name and ensures sub records are always arrays of arrays
```

Which is correct?

If i comment out the line that calls that method, i do get the data as expected. ... Unfortunately, this also raises the following error in Ember: "You must include an `id` for client@model:agency: in an object passed to `push`"

I should add that all of this was working fine with the plural name, except that i'm finding it impossible to figure out how to display any of the agency attrs in the template. While hunting that down (unsuccessfully) i came across the example showing that is should be singular.

Hope you can follow all that. Argh! Ember-Data is a freaking monster.

**Comment by justinyost** [comment]
Sorry for the delayed response, I was travelling and didn't get a chance to look at this till now.

Ok, so let's take this piece by piece:

This plugin doesn't match Ember Data specs exactly, because it in fact is designed to match the http://emberjs.com/api/data/classes/DS.ActiveModelAdapter.html not the normal RestAdapter. This is documented: https://github.com/loadsys/CakePHP-Serializers/blob/master/README.md This means that you shouldn't expect everything to match the EmberData specs 100% and things will look different.

This means the Plugin is correct given the spec it is matching, which isn't the EmberData spec, so yeah it may look different.

Hopefully that solves at least the first issue.

If you still have issues adding Agency attributes, feel free to reach out and ask.
