### ISSUE TITLE
Should Serializer try to detect Cake conventional `set()`s?

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Serializers#33]
Right now, the serializer dictates that controller actions perform a `$this->set('data', $findResults);` instead of the "stock" baked actions, that set a variable name that matches the controller/model name like `$this->set('cats', $cats);`

Does it make sense for Serializers to attempt to use this key? Instead of $data? As a fallback when $data is empty?

**Comment by jtyost2** [comment]
Few questions come to mind?

1. What happens if `$data` is supposed to be empty?
2. How do we determine the appropriate view variable?
3. Do we ignore the first, and select the one that matches the controller (following bake's) standard?

The first is the question I'm most concerned about.

I suppose the easy solution is, if `$data` is empty, check for the view variable that matches the model name, then if it is also empty or not set, use the empty `$data`. 

Hmm, now that I'm thinking about it, this is a good question, should be done.

`$controller/model` match should be the primary, then fallback to `$data`, easy solution, better moving forward and would still work for our use case.

**Comment by jtyost2** [comment]
Assigning to myself to be completed at some point.

**Comment by beporter** [comment]
Regarding point 1: We can differentiate between "not set" and "set, but empty" right? If so, I'd say that's the litmus test to determine whether to "use" `$data` or to try to fall back to `$modelName`. 

On point 2: The serializer must already be able to determine the proper model name because it has to try to instantiate a custom ModelNameSerializer class. That's the same (inflected) variable name to look for.

On 3: I'm still not even saying this is necessarily a good idea. If anything, it might have been wiser to strictly follow Cake's established conventions and **only** recognize a view var named after the current controller/model.
